apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: django-app
data:
  DB_HOST: "postgres-service"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "hostpidor"
  DB_NAME: "postgres"
  DB_PORT: "5432"
  STATIC_ROOT: "/data/static"
